services:

    # Admin product variant form extensions
    gewebe_sylius_product_deposit_plugin.form.extension.type.product_variant:
        class: Gewebe\SyliusProductDepositPlugin\Form\Extension\ProductVariantTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType, priority: -5 }

    # Admin new deposit form type
    gewebe_sylius_product_deposit_plugin.form.type.channel_deposit:
        class: Gewebe\SyliusProductDepositPlugin\Form\ChannelDepositType
        arguments:
            - '%gewebe_product_variant_deposit.model.channel_deposit.class%'
            - ['sylius']
        tags:
            - { name: form.type}
