services:

    # Admin product variant menu listener
    gewebe_sylius_product_deposit_plugin.listener.admin.product_variant.form.menu_builder:
        class: Gewebe\SyliusProductDepositPlugin\Menu\AdminProductVariantFormMenuListener
        arguments:
            - '@Sylius\Bundle\ThemeBundle\Translation\ThemeAwareTranslator'
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.product_variant.form, method: addItems }
