services:

    # Product variants deposit provider
    gewebe_sylius_product_deposit_plugin.provider.product_variants_deposit:
        class: Gewebe\SyliusProductDepositPlugin\Provider\ProductVariantsDepositsProvider

    # Template helper
    gewebe_sylius_product_deposit_plugin.templating.helper.product_variants_deposit:
        class: Gewebe\SyliusProductDepositPlugin\Templating\Helper\ProductVariantsDepositHelper
        arguments: ['@gewebe_sylius_product_deposit_plugin.provider.product_variants_deposit']
        tags:
            - { name: templating.helper, alias: gewebe_product_variants_deposit }

    # Template twig extension
    gewebe_sylius_product_deposit_plugin.twig.extension.product_variants_deposit:
        class: Gewebe\SyliusProductDepositPlugin\Templating\Helper\ProductVariantsDepositExtension
        arguments: ['@gewebe_sylius_product_deposit_plugin.templating.helper.product_variants_deposit']
        tags:
            - { name: twig.extension }
