# Overriding product variant resource
#sylius_product:
#  resources:
#    product_variant:
#      classes:
#        model: Gewebe\SyliusProductDepositPlugin\Entity\ProductVariant

# New channel deposit resources
sylius_resource:
  resources:
    gewebe_product_variant_deposit.channel_deposit:
      classes:
        model: Gewebe\SyliusProductDepositPlugin\Entity\ChannelDeposit
        interface: Gewebe\SyliusProductDepositPlugin\Entity\ChannelDepositInterface
        form: Gewebe\SyliusProductDepositPlugin\Form\ChannelDepositType
