
sylius_ui:
  events:
    sylius.shop.product.show.right_sidebar:
      blocks:
        deposit:
          template: '@GewebeSyliusProductDepositPlugin/Product/Show/_deposit.html.twig'
          priority: 29

    sylius.shop.layout.javascripts:
      blocks:
        deposit: '@GewebeSyliusProductDepositPlugin/Product/Show/_deposit_javascript.html.twig'
